# Site settings
name: Zy's blog
email: printzy@126.com
author: ZY
url: https://zydemo.github.io/
resume_site: ''
github: https://zydemo.github.io/
baseurl: ''
description: 人生苦短，我用Python！
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
# 一页有几篇文章
paginate: 10
paginate_path: 'page:num'

# 设置时区，如果不设置每个文章头部date结尾需添加 +0800
# timezone: Asia/Shanghai

## Gem
gems: [jekyll-paginate]
# highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'createNew_MDFile']

github_username: zydemo

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

